### ISSUE TITLE
install_scl_repo Error

### ISSUE THREAD

**Issue by andreimahu** [poise/poise-languages#10]
**Error: 'rhel-server-rhscl-7-rpms' does not match a valid repository ID.**
It seems to be the same as https://github.com/poise/poise-languages/issues/8

Error popped up within the following parameters:
RHEL-7.3
poise_languages 2.1.1
poise_python 1.6.0
chef-client 13.1.31

Full Error Log & Stacktrace:
`python_runtime[2] (poise-python::default line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: poise_languages_scl[python27] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/mixin.rb line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[subscription-manager repos --enable rhel-server-rhscl-7-rpms] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb line 110) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1' ---- Begin output of subscription-manager repos --enable rhel-server-rhscl-7-rpms ---- STDOUT: Error: 'rhel-server-rhscl-7-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories. STDERR: ---- End output of subscription-manager repos --enable rhel-server-rhscl-7-rpms ---- Ran subscription-manager repos --enable rhel-server-rhscl-7-rpms returned 1`

**Comment by coderanger** [comment]
Are you on a cloud version of RHEL?

**Comment by andreimahu** [comment]
Yes, I am testing this suggestion at the moment https://github.com/poise/poise-languages/pull/9

**Comment by andreimahu** [comment]
I can confirm that the suggestion https://github.com/poise/poise-languages/pull/9 worked. Closing the issue.
