### ISSUE TITLE
Python cannot be installed on RHEL 7.2 (Bug in install_scl_repo)

### ISSUE THREAD

**Issue by statusfailed** [poise/poise-languages#8]
# Problem

Python package (e.g., `python35`) cannot be installed on RedHat Enterprise Linux. A typical error from running `chef-client` is:

    * poise_languages_scl[rh-python35] action install
      * execute[subscription-manager repos --enable rhel-server-rhscl-7-rpms] action run (skipped due to not_if)
      * ruby_block[flush_yum_cache] action run
        - execute the ruby block flush_yum_cache
      * yum_package[rh-python35] action install
        * No candidate version available for rh-python35
        * No candidate version available for rh-python35
        * No candidate version available for rh-python35
        * No candidate version available for rh-python35
        * No candidate version available for rh-python35
        * No candidate version available for rh-python35
        ================================================================================
        Error executing action `install` on resource 'yum_package[rh-python35]'
        ================================================================================

# Cause

Note the line below indicates the `rhel-server-rhscl-7-rpms` repository was not subscribed to:

    execute[subscription-manager repos --enable rhel-server-rhscl-7-rpms] action run (skipped due to not_if)

This is due to the following code from [here](https://github.com/poise/poise-languages/blob/master/lib/poise_languages/scl/resource.rb#L105):

          execute "subscription-manager repos --enable #{repo_name}" do
            not_if { shell_out!('subscription-manager repos --list').stdout.include?(repo_name) }
          end

In particular, the command `subscription-manager repos --list` lists *all* repos, _including disabled_ repos, so this command will never be run.

# Suggested Fix

A fixed version should replace the `--list` command with `--list-enabled`, i.e.:

          execute "subscription-manager repos --enable #{repo_name}" do
            not_if { shell_out!('subscription-manager repos --list-enabled').stdout.include?(repo_name) }
          end

**Comment by coderanger** [comment]
Aha, thank you! Down side of writing code that I can't test :) Will get this fixed up.
